apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z8fa
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0028-tenant/tkrw-pr712-0075-0028-app/devfile-sample-z8fa@sha256:5fb2b2cccec867568a7223cc0d719273af5a6e09d562e064617a9dc5cb71b10e
        name: my-nodejs
        resources: {}
status: {}
